default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: app408_activeJob_development

test:
  <<: *default
  database: app408_activeJob_test

production:
  <<: *default
  database: app408_activeJob_production
  username: app408_activeJob
  password: <%= ENV['APP408_ACTIVEJOB_DATABASE_PASSWORD'] %>
