# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37b45b30d7a050b22b99c0447dbf00fea99316c6fb965a7996b74dfedfb8b69dc6690720a3abf40b5778e4e007ef9d7ef93580816c475db33fe0511678e62427

test:
  secret_key_base: 0feb22fc0f640f8263ce5d282a34c65aa3471b153ba7ae990a4e0f4861519789cd1f403f8d3398a28aa4cc7b6f3749a98ce812d0c1b3d911dd509b08852412ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
